### ISSUE TITLE
Normalized  mortality per age group

### ISSUE THREAD

**Issue by Wolvverine** [dkobak/excess-mortality#11]
In order for the picture to be realistic, you need to take into account the age groups and the mortality rate in them in previous years. Otherwise you get the wrong picture when you suddenly have spikes in certain age groups of the population. And the different demographics of countries.

https://www.cebm.net/covid-19/excess-mortality-across-countries-in-2020/

Example for Sweden:
![167244489_10158620283749071_2274594161024859779_n](https://user-images.githubusercontent.com/5873929/134903856-eb68c8e5-e1f8-4310-93ea-013a4fd1c88a.jpg)

**Comment by dkobak** [comment]
Thanks for your comment, but unfortunately for most countries in the World Mortality Dataset there is no information available by age brackets (only population total), so we could not perform any kind of age-resolved analysis.
