### ISSUE TITLE
Monthly data by date of death for Russia

### ISSUE THREAD

**Issue by keepgoing1995** [dkobak/excess-mortality#14]
@dkobak  Are you planning to update the monthly data by date of death for the regions of Russia? I noticed it has already been corrected for the country, but not for the administrative areas.

**Comment by keepgoing1995** [comment]
@dkobak  Is the monthly data by date of death even available for all regions? Because I just assumed that it it, because you updated the country-level data.

**Comment by dkobak** [comment]
Yes, the monthly data are available. I had for a while no, but didn't get around updating the repository. I did it now. Let me know if you have any questions.

Going forward, I am not currently planning to update this analysis with 2024+ data.
