### ISSUE TITLE
readme: > 50K should be 50M? 

### ISSUE THREAD

**Issue by mpaolo** [dkobak/excess-mortality#6]
In the readme:

_Top-10 countries in the World Mortality Dataset according to different metrics (only countries with over **50,000** population are shown):_

guess it should be 50,000,000

**Comment by dkobak** [comment]
No, why? It means 50 thousand. Filters out San Marino and Lichtenstein that would otherwise enter this chart.

**Comment by mpaolo** [comment]
oops, sorry - overlooked the 'Top 10' as the range limit ... indeed the list for pop>50M would be longer than 10 anyway :/
