### ISSUE TITLE
all-countries.ipynb: got HTTPError 'forbidden' for df_official 

### ISSUE THREAD

**Issue by mpaolo** [dkobak/excess-mortality#7]
I'm running the code in local instance of Jupiter, at some point got an error for df_official. I see now there's a hack in the code as chunk 3, but my fix was simply

`df_official = pd.read_csv('https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv?raw=true')`

seems OWD wants to move data traffic onto github. Just checked this URL and original from owd and they're in sync. Indeed, now http://covid.ourworldindata.org redirects to above github account so also old original URL should just work without hack.

**Comment by dkobak** [comment]
Oh! Thanks! I will use it in the next update :)

**Comment by dkobak** [comment]
Pushed an update with this fix!
