### ISSUE TITLE
place 'placeholder' chunks in if() switch

### ISSUE THREAD

**Issue by mpaolo** [dkobak/excess-mortality#8]
I suggest to put 'placeholder' chunks in if() switch like

```
if (1):
    country='Sweden'
    X = allcountries[country][0]
    baseline = allcountries[country][1]
    ...
```
that's quicker &  easier (for me at least) than (un)comment all relevant lines or even change the cell type (code, markup, raw nbr in Jupyter) to (de)activate the chunk as needed

**Comment by dkobak** [comment]
Thanks for suggestion but I'm actually going to delete all this from the notebook.
