### ISSUE TITLE
incomplete all-countries.png caption

### ISSUE THREAD

**Issue by mpaolo** [dkobak/excess-mortality#9]
In my local copy I adjusted the caption according to code / preprint.
Use/adjust as you see fit in case.

```
--- figtext     2021-02-22 13:15:30.275003847 +0100
+++ figtextmp   2021-02-23 12:05:00.018288814 +0100
@@ -2 +2 @@
-'Data: World Mortality Dataset, github.com/akarlinsky/world_mortality. '
+'Data: World Mortality Dataset, github.com/akarlinsky/world_mortality, github.com/datasets/, github.com/owid/ . '
@@ -4,5 +4,6 @@
-'Excess mortality is computed relative to the baseline extrapolated from 2015–19. '
-'Red number: excess mortality starting from the first officially reported covid19 death.\n'
-'Gray: as a % of baseline yearly deaths. '
-'Black: per 100,000 population. '
-'Blue: ratio to the daily reported covid19 deaths over the same period. '
+'Excess mortality is computed relative to the baseline extrapolated from 2015–2019. '
+'Lines: black: baseline, gray: 2015-2019, red: 2020, magenta: 2021\n'
+'Numbers: red: estimated excess mortality starting from the first officially reported covid19 deaths up to last available official mortality data,\n'
+'gray: as a % of baseline yearly deaths. black: per 100,000 population, '
+'blue: ratio to the daily reported covid19 deaths over the same period.\n'
+'(*) less war / heatwave excess deaths.\n'
```

Caution though to define the blu ratio as _undercount_ in general, although there are some glaring cases: e.g. for Italy it's documented (also in your ref. Beaney,2020) that ca. 1/3 excess deaths are non-covid19 due to missed cares either for fear of contagion, lockdown measures, overburden of care facilities:
- in latest news https://www.adnkronos.com/covid-30mila-morti-per-altre-malattie-trascurate_2difOiSOAXHlHbkOCeX1H5
- an earlier (1st wave) analysis with geo/age structure considerations https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-020-09335-8
- latest IT national stats report https://www.istat.it/it/archivio/252168 (sorry, seems EN version not available)

And e.g. for USA _For 6% of the deaths, COVID-19 was the only cause mentioned_ of the covid19 counts while for the rest it's a matter of choosing the most (often more politically than medically) convenient label https://www.cdc.gov/nchs/nvss/vsrr/covid_weekly/index.htm#Comorbidities with a number of _collateral damages_ like increase in drug abuse https://jamanetwork.com/journals/jama/fullarticle/2776212 and psycho issues e.g. https://www.bmj.com/content/371/bmj.m4352.short

**Comment by dkobak** [comment]
When Michelozzi et al. write that "COVID-19 deaths accounted for half of total excess mortality in both areas" (https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-020-09335-8), they mean *officially reported* COVID-19 deaths. So this is consistent with undercount.

I understand the concern, but so far I haven't seen ANY actual numerical data from ANYWHERE which would suggest non-trivial contribution of non-COVID deaths (deaths without COVID infection) to the excess mortality.
